#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define MASTER_ACCESS_PASSWORD "SultanLenvu"

#define DEFAULT_FIRMWARE_FILE_PATH "../Firmware/firmware.hex"
#define DEFAULT_JLINKEXE_FILE_PATH "../JLink/JLink.exe"
#define DEFAULT_JLINK_SCRIPT_FILE_NAME "JLinkScript.jlink"

#define USER_DATA_FLASH_START_ADDRESS "0x0801F000"
#define USER_DATA_FLASH_SIZE 0x1000
#define USER_DATA_FLASH_END_ADDRESS "0x0801FFFF"

#endif // DEFINITIONS_H
