name: build PersoClient
run-name: build PersoClient
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-23.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build and package PersoClient
        run: |
          cd ${{ gitea.workspace }}
          GITREF=$(git describe --abbrev)
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
          mkdir -p persoclient_$GITREF-1_amd64
          DESTDIR=persoclient_$GITREF-1_amd64 ninja install
          mkdir persoclient_$GITREF-1_amd64/DEBIAN
          sed -e "s/@VERSION@/$GITREF/g" < ../DEBIAN/control.in > persoclient_${{ gitea.ref_name }}-1_amd64/DEBIAN/control
          cp ../DEBIAN/postinst persoclient_$GITREF-1_amd64/DEBIAN/
          dpkg-deb --build --root-owner-group persoclient_$GIREF-1_amd64
