name: build PersoClient
run-name: build PersoClient
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-23.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build and package PersoClient
        run: |
          cd ${{ gitea.workspace }}
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
          ninja manual
          mkdir -p persoclient_1.0.0-1_amd64
          DESTDIR=persoclient_1.0.0-1_amd64 ninja install
          mkdir persoclient_1.0.0-1_amd64/DEBIAN
          sed -e "s/@VERSION@/1.0.0/g" < ../DEBIAN/control.in > persoclient_1.0.0-1_amd64/DEBIAN/control
          cp ../DEBIAN/postinst persoclient_1.0.0-1_amd64/DEBIAN/
          dpkg-deb --build --root-owner-group persoclient_1.0.0-1_amd64
