name: build, package and put PersoClient to the repository
run-name: build, package and put PersoClient to the repository
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-23.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build and package PersoClient
        run: |
          cd ${{ gitea.workspace }}
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja ..
          ninja
          ninja manual
          mkdir -p persoclient_${{ gitea.ref_name }}-1_amd64
          DESTDIR=persoclient_${{ gitea.ref_name }}-1_amd64 ninja install
          mkdir persoclient_${{ gitea.ref_name }}-1_amd64/DEBIAN
          sed -e "s/@VERSION@/${{ gitea.ref_name }}/g" < ../DEBIAN/control.in > persoclient_${{ gitea.ref_name }}-1_amd64/DEBIAN/control
          cp ../DEBIAN/postinst persoclient_${{ gitea.ref_name }}-1_amd64/DEBIAN/
          dpkg-deb --build --root-owner-group persoclient_${{ gitea.ref_name }}-1_amd64
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: persoclient_${{ gitea.ref_name }}-artifacts
          path: |
            build/persoclient_${{ gitea.ref_name }}-1_amd64.deb
            Doc/manual/manual.pdf
            supplemental/PersoClient.ini
  deploy:
    runs-on: ubuntu-23.04
    steps:
      - name: Fetch package artifact
        uses: https://github.com/actions/download-artifact@v3
        with:
          name: persoclient_${{ gitea.ref_name }}-artifacts
      - name: Deploy and regenerate repository
        run: |
          cp persoclient_${{ gitea.ref_name }}-1_amd64.deb /var/www/repo/pool/internal
          cd /var/www/repo/
          apt-ftparchive packages pool/internal > dists/mantic/internal/binary-amd64/Packages
          echo "Archive: mantic" > dists/mantic/Release
          echo "Suite: mantic" >> dists/mantic/Release
          echo "Components: internal" >> dists/mantic/Release
          echo "Architectures: amd64" >> dists/mantic/Release
          apt-ftparchive release dists/mantic >> dists/mantic/Release
      - name: trigger Ansible playbook to make clients upgrade
        run: |
          CONFIG_FILE=$(realpath PersoClient.ini)
          MANUAL_FILE=$(realpath manual.pdf)
          cd $HOME/ansible-upgrade
          ansible-playbook -i inventory.ini playbook.yaml -u root -e "config_file=$CONFIG_FILE,manual_file=$MANUAL_FILE"
